# -*- coding: utf-8 -*-
"""Integrate Twilio_RANI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfMBK40sn-tpbomUhBJZSofauq_gnwOY
"""

!pip install twilio

from twilio.rest import Client

# Import Twilio's Client class from twilio.rest module
from twilio.rest import Client
# Replace 'account_id' with your actual Twilio Account SID
account_sid = 'Twilio Account SID'
# Replace 'auth_token' with your actual Twilio Auth Token
auth_token = 'Twilio Auth Token'

# Create a Twilio client instance with Account SID and Auth Token
client = Client(account_sid, auth_token)

# Define a function to send SMS alerts
def sendSms():
    # Create an SMS message using client.messages.create method
    # Replace '1-638-318-3897' with your actual Twilio phone number
    # Replace '+918776667125' with the recipient's phone number
    message = client.messages.create(
        from_='+916756453456',  # Twilio phone number (sender)
        body='Alert ',          # SMS message body
        to='+918776667125'      # Recipient's phone number
    )

    # Print the unique message SID (identifier) for debugging purposes
    print(message.sid)
#Call the sendSms function to send an SMS alert
sendSms()